packages:
  - "apps/*"
  - "packages/*"

nodeLinker: hoisted
injectWorkspacePackages: true
virtualStoreDir: .pnpm
virtualStoreDirMaxLength: 24

overrides:
  "@types/superagent": "8.1.10"
  "react": "19.2.3"
  "react-dom": "19.2.3"
  "ws": "8.21.0"

allowBuilds:
  "@firebase/util": true
  "esbuild": true
  "msgpackr-extract": true
  "protobufjs": true
