packages:
  - "apps/*"
  - "packages/*"

overrides:
  "@types/superagent": "8.1.10"
  "ws": "8.21.0"

allowBuilds:
  "@firebase/util": true
  "esbuild": true
  "msgpackr-extract": true
  "protobufjs": true
